### PR TITLE
Linting with flake8

### PR DESCRIPTION
**Pull request by GitRon**
Did some basic linting with flake8. Hope you agree with me on this one 🙂

### CODE REVIEW

**Comment by lociii** [comment]
Feel free to add linting to the GitHub actions so that we will maintain a proper state in the future too.

**Comment by GitRon** [comment]
I am not super familiar with github actions as we are using Gitlab. I saw in the docs that you need to set a python version. Which should I take there? Latest? 3.10?

**Comment by lociii** [comment]
The lowest supported Python version atm is 3.7 - I'd also base the linter on it.

**Comment by GitRon** [comment]
@lociii Alright, I'll have a look the other day.

**Pull request merged**
