### PR TITLE
Add SameLengthText scrubber

### PR DESCRIPTION
**Pull request by md-f**
This adds a scrubber that scrubs a field maintaining the field original text length.

### CODE REVIEW

**Comment by meshy** [comment]
It should be noted that this is of particular use when a field has a length limit that is less than the length of the hash.

**Comment by costela** [comment]
Thanks for the contribution!
This seems like a very useful addition in general, but I'm a bit unsure about the implementation. The dependency on postgres functions limits its usefulness a bit. Plus, I see no reason why this couldn't be the default behaviour of the `Hash` scrubber.

I have a rough sketch for an alternative in mind:
- changing the way we initialize scrubbers in `scrub_data.Command.handle()` to pass the `Field` object instead of `field.name`
- have `Hash` check `Field.max_length` (if appropriate) and use `LEFT(MD5(<field.name>),<field.max_length>)` as template.

This would make it slightly more standards compatible, and seems like a more extensible solution. It would break any custom scrubbers expecting field names for initialization, but I think the minor breakage should be worth it.

Thoughts?

**Comment by meshy** [comment]
We like the idea of making this behaviour the default, thank you!

We've opened #7 so that we can add tests to this PR that prove whatever solution we come up with works on multiple databases.

Thanks for the feedback!

**Comment by md-f** [comment]
Thank you both, excellent suggestions, I pushed this, but it is still a work in progress.

**Comment by costela** [comment]
@md-f thanks again for all the work!
I've also started on my own implementation of this idea and have something preliminary working. I'll push it tomorrow morning and we can see if its enough for your needs.

**Comment by costela** [comment]
hey @md-f can you please take a look at the [pass_field_to_scrubbers](/regiohelden/django-scrubber/tree/pass_field_to_scrubbers) branch?
It seems we were working on similar approaches.

**Comment by md-f** [comment]
Hi @costela looks very good to me, I took the liberty to try and implement this PR based on your earlier comment, not knowing you would have submitted a branch so quickly! 
I'm certainly more than happy with your solution, please feel free to do whatever you prefer with my code/PR.

**Comment by costela** [comment]
I've merged my work to master. Could you maybe trim this PR down to the test-cases? At least this way your work wasn't completely wasted :wink:

**Comment by meshy** [comment]
@costela FYI this has now been rebased, and only includes the test.

We'd greatly appreciate a new release, if you're planning on making one soon! :)

**Pull request merged**
