### PR TITLE
Readme extended with "Logging" part and added example

### PR DESCRIPTION
**Pull request by GitRon**
Hi @costela 

here is my suggestion to help people get up and running even faster.

Best 
Ronny

### CODE REVIEW

**Comment by GitRon** [comment]
@costela Any ideas about this PR? OK for you?

**Comment by costela** [comment]
Hi @GitRon 

I'm not sure about this. I wanted to check what's the behavior with a clean django install to be sure, but I suspect this works out-of-the-box.  
Assuming I'm right, this would mean we'd be adding something to the README just to counter-act misconfiguration on the user's side, which IMHO doesn't feel quite right.

But I'll leave this decision up to someone else in the @RegioHelden team. This is just my 0.2¢.

**Comment by MounirMesselmeni** [comment]
I personally agree with @costela

**Comment by GitRon** [comment]
If it is this way, I agree as well 😄 

But I jused scrubber in two different projects and it didnt log anything. 🤷‍♂

**Comment by lociii** [comment]
@GitRon what is your logging config in these projects looking like?

**Comment by GitRon** [comment]
Hi @lociii 

here is one example, looks more or less the same in all my projects:

Thx for your help!

```
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(asctime)s - %(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
        },
        'simple': {
            'format': '%(asctime)s - %(levelname)s %(message)s'
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse'
        }
    },
    'handlers': {
        'cronjob_handler': {
            'level': 'DEBUG',
            'class': 'django_db_logger.db_log_handler.DatabaseLogHandler',
            'formatter': 'verbose',
        },
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler'
        },
        'email_handler': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'formatter': 'verbose',
            'filename': os.path.join(str(APPS_DIR), 'logs', 'email.log')
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
    },
    'loggers': {
        'cronjob_logger': {
            'handlers': ['console', 'cronjob_handler'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['mail_admins'],
            'level': 'ERROR',
            'propagate': True,
        },
        'email_logger': {
            'handlers': ['console', 'email_handler'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'django.db.backends': {
            'level': 'ERROR',
            'handlers': ['mail_admins'],
            'propagate': False,
        },
        'sentry.errors': {
            'level': 'DEBUG',
            'handlers': ['mail_admins'],
            'propagate': False,
        },
        'django_scrubber': {
            'level': 'DEBUG',
            'handlers': ['console'],
            'propagate': True,
        },
    }
}

```

**Comment by lociii** [comment]
Sorry for the last response.
Can you please check if something is logged, when you set django to DEBUG and skip the django_scrubber logging config?

```python
LOGGING = {
    'loggers': {
        'django': {
            'level': 'DEBUG',
            'handlers': ['console'],
            'propagate': True,
        },
    },
}
```

**Comment by GitRon** [comment]
Nope, zero log output. 🤷‍♂

**Comment by lociii** [comment]
Then I'm fine with the change.
Thanks for your support and your patience :)

**Comment by GitRon** [comment]
No worries! Thanks a lot! Happy to contribute!

**Pull request merged**
