### PR TITLE
Added hints to docs about overridden queryset method in manager

### PR DESCRIPTION
**Pull request by GitRon**
Hi @costela 

after our discussion the other day I thought if we don't solve the issue, we could at least inform people about it.

Ok for you?

Fixes https://github.com/RegioHelden/django-scrubber/issues/15

Best  
Ronny

### CODE REVIEW

**Comment by costela** [comment]
Hi @GitRon ,

Thanks for the PR!

I'm a bit conflicted about this change, for similar reasons as outlined in https://github.com/RegioHelden/django-scrubber/pull/17#issuecomment-557889737. We'd be basically adding a warning to the README about usage which is IMHO pretty clearly an anti-pattern.  
I think this is a bit of a slippery slope.

Furthermore, I don't think this a _limitation_ of `django-scrubber`: it's a design decision.

If it turns out I'm overlooking something and there *are* valid use-cases for this "invisible rows" pattern, than we can either revisit [your suggestion of always using the base manager](https://github.com/RegioHelden/django-scrubber/issues/15#issuecomment-554896072), or turn this PR into something like a new FAQ.  
Anyway I'll let this sit a while to see of someone else has any opinion on it.

**Comment by GitRon** [comment]
Hi @costela 

ok, I agree. I too think its a bad way to code. But maybe we can find a different work than `limition` so people are warned?

Best
Ronny

**Comment by GitRon** [comment]
@costela I changed the title. Agreed?

**Comment by lociii** [comment]
@GitRon thanks for your proposal but I will reject the pull request as this is not an issue specific to this library. Every other library relying on ```objects``` will be broken / misbehaving. Even the Django admin will not function as expected.

**Pull request closed without merging**
